name: portfolio
services:
  nextjs-app:
    container_name: 'nextjs-app'
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
    networks:
      - portfolio-network
    ports:
      - 3000:3000

networks:
  portfolio-network:
    driver: bridge
